### 8.7    异常说明作为类型的一部分

自 C++17 起，异常处理说明成为了函数类型的一部分。也就是说，下面的两个函数现在具有不同的类型：

```c++
void fMightThrow();
void fNoexcept() noexcept;      // 不同类型
```

在 C++17 前，这两个函数有相同的类型。一个后果是，将可能抛出的函数传递给保证不抛出的函数指针现在是一个错误：[^4]

```c++
void (*fp)() noexcept;  // 指向不抛出的函数的指针
fp = fNoexcept;         // 正确
fp = fMightThrow;       // C++17 起错误
```

[^4]:在 C++17 前这似乎就是错误的，但至少 g++ 确实允许这样的代码（即使在 pedantic 模式下）。

当然，将不抛出的函数传递给不保证不抛出的函数指针仍然是合法的：

```c++
void (*fp2)();          // 指向可能抛出的函数的指针
fp2 = fNoexcept;        // 正确
fp2 = fMightThrow;      // 正确
```

因此，该新特性不会破坏尚未将 `noexcept` 用于函数指针的程序，但能确保你现在不再违反函数指针中的 `noexcept` 要求（这可能有充分的理由破坏现有程序）。

不允许使用不同的异常说明重载具有相同签名的函数名（就像不允许重载只有返回类型不同的函数）：

```c++
void f3();
void f3() noexcept;     // 错误
```

注意所有其它规则都不影响。例如，仍然不允许忽略基类的 `noexcept` 说明：

```c++
class Base {
 public:
  virtual void foo() noexcept;
  ...
};

class Derived : public Base {
 public:
  void foo() override;  // 错误：没有覆盖
  ...
};
```

这里，派生类的成员函数 `foo()` 有不同的类型，因此它不能覆盖基类的 `foo()`。该代码依旧不能编译。即使没有 `override` 说明符该代码也不能编译，因为我们仍然不能通过更宽松的抛出说明来重载。

##### 使用条件异常说明

当使用条件异常说明时，函数的类型依赖于条件是真还是假：

```c++
void f1();
void f2() noexcept;
void f3() noexcept(sizeof(int)<4);  // 和 f1() 或 f2() 的类型相同
void f4() noexcept(sizeof(int)>=4); // 和 f3() 的类型不同
```

此处，`f3()` 的类型依赖于编译代码时的条件类型：

+ 如果 `sizeof(int)` 得到 4（或更多），则生成的签名是
  ```c++
  void f3() noexcept(false);    // 和 f1() 的类型相同
  ```
+ 如果 `sizeof(int)` 得到小于 4 的值，则生成的签名是
  ```c++
  void f3() noexcept(true);     // 和 f2() 的类型相同
  ```
  
因为 `f4()` 的异常条件和 `f3()` 的相反，因此 `f3()` 和 `f4()` 的类型始终不同（即，其中一个指定可能抛出，而另一个指定不抛出）。

“老式”的空抛出说明仍然可用，但自 C++11 起已经弃用：

```c++
void f5() throw();  // 和 void f5() noexcept 相同，但被弃用
```

不再支持带有实参的动态异常说明（它们自 C++11 起也被弃用了）：

```c++
void f6() throw(std::bad_alloc);    // 错误：C++17 起不合法
```

##### 对泛型库产生的影响

使得 `noexcept` 声明成为类型的一部分可能会对泛型库产生一些影响。例如，下面的程序直到 C++14 都是有效的，但 C++17 中不再能编译：

*lang/noexceptcalls.cpp*

```c++
#include <iostream>

template<typename T>
void call(T op1, T op2)
{
  op1();
  op2();
}

void f1() {
  std::cout << "f1()\n";
}
void f2() noexcept {
  std::cout << "f2()\n";
}

int main()
{
  call(f1, f2); // C++17 起错误
}
```

问题在于，从 C++17 起，`f1()` 和 `f2()` 具有不同的类型，因此当实例化函数模板 `call()` 时，编译器不能为这两个类型找到公共类型 `T`。

C++17 起，你必须使用两个不同的模板类型形参以确保这还能编译：

```c++
template<typename T1, typename T2>
void call(T1 op1, T2 op2)
{
  op1();
  op2();
}
```

如果你想要或必须重载所有可能的函数类型，现在也必须加倍重载。例如，这适用于标准类型特性 `std::is_function<>` 的定义。主模板被定义，因此通常类型 `T` 不是函数：

```c++
// 主模板（通常类型 T 不是函数）：
template<typename T> struct is_function : std::false_type { };
```

该模板派生自 `std::false_type`（见 33.2 节），因此通常 `is_function<T>::value` 对任意类型 `T` 产生 `false`。

对于所有*是*函数的类型，存在派生自 `std::true_type`（见 33.2 节）的部分特化，因此对于这些类型，成员 `value` 产生 `true`：

```c++
// 对所有函数类型的部分特化：
template<typename Ret, typename... Params>
struct is_function<Ret (Params...)> : std::true_type { };

template<typename Ret, typename... Params>
struct is_function<Ret (Params...) const> : std::true_type { };

template<typename Ret, typename... Params>
struct is_function<Ret (Params...) &> : std::true_type { };

template<typename Ret, typename... Params>
struct is_function<Ret (Params...) const &> : std::true_type { };
...
```

在 C++17 前已经有 24 个部分特化了，因为函数类型可以拥有 `const` 与 `volatile` 限定符和左值（`&`）与右值（`&&`）引用限定符，并且你需要为带有可变参数列表的函数提供重载。

现在，在 C++17 中，通过为所有这些部分特化添加 `noexcept` 限定符，部分特化的数量翻倍，所以我们现在有 48 个部分特化：

```c++
...
// 对所有带有 noexcept 的函数类型的部分特化：
template<typename Ret, typename... Params>
struct is_function<Ret (Params...) noexcept> : std::true_type { };

template<typename Ret, typename... Params>
struct is_function<Ret (Params...) const noexcept> : std::true_type { };

template<typename Ret, typename... Params>
struct is_function<Ret (Params...) & noexcept> : std::true_type { };

template<typename Ret, typename... Params>
struct is_function<Ret (Params...) const& noexcept> : std::true_type { };
...
```

对于传递函数或函数指针到需要 `noexcept` 的位置的代码，没有实现 `noexcept` 重载的库可能不能编译。